### ISSUE TITLE
add ICIP 2021 paper

### ISSUE THREAD

**Issue by huckiyang** [hitachi-speech/hitachi-speech.github.io#1]
Hello @hshota0530 could you help us to add the IEEE ICIP 2021 paper to the computer vision list with Quan Kong and Mohit Chhabra and the team. Thanks!

Robust Unsupervised Multi-Object Tracking in Noisy Environments

- https://ieeexplore.ieee.org/document/9506029
- bib
```bib
@INPROCEEDINGS{9506029,  author={Huck Yang, C.-H. and Chhabra, Mohit and Liu, Y.-C. and Kong, Quan and Yoshinaga, Tomoaki and Murakami, Tomokazu},  booktitle={2021 IEEE International Conference on Image Processing (ICIP)},   title={Robust Unsupervised Multi-Object Tracking In Noisy Environments},   year={2021},  volume={},  number={},  pages={2239-2243},  doi={10.1109/ICIP42928.2021.9506029}}
```

**Comment by shota-horiguchi** [comment]
Thanks for your information. I've updated the list.
